apiVersion: v1
kind: Secret
metadata:
  name: kikos-api-secrets
  namespace: kikos
type: Opaque
stringData:
  # ======================
  # Database
  # ======================
  DATABASE_USER: "<db_user>"
  DATABASE_PASS: "<db_password>"
  DATABASE_NAME: "<db_name>"
  DATABASE_HOST: "<db_host>"
  DATABASE_PORT: "<db_port>"
  DATABASE_URL: "postgresql://<db_user>:<db_password>@<db_host>:<db_port>/<db_name>"
  BETTER_AUTH_SECRET: "<better_auth_secret>"
  BETTER_AUTH_URL: "<better_auth_url>"
