apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kikos
type: Opaque
stringData:
  POSTGRES_DB: "<db_db>"
  POSTGRES_USER: "<db_user>"
  POSTGRES_PASSWORD: "<db_password>"
  POSTGRES_PORT: "<db_port>"
