apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teragestor-cert
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.teragestor.com.br
