apiVersion: v1
kind: Secret
metadata:
  name: kikos-web-secrets
  namespace: kikos
type: Opaque
stringData: 
  BETTER_AUTH_URL: "<BETTER_AUTH_URL>"
  SECRET_CLIENT_COOKIE_VAR: {"key_ops":["encrypt","decrypt"],"ext":true,"kty":"oct","k":"NNfUvT4_oXApYLsJ1Z2l5BXDFANRJmHJD5x1VsNRTyQ","alg":"A256CBC"}
